input:
    input_path: ./test
    data_fname: test_data.hdf5
    randoms1_fname: test_randoms.hdf5
    randoms2_fname: test_randoms.hdf5

output:
    output_path: ./test
    displaced_catalog_fname: data_rec.hdf5
    shifted_random_catalog_fname: rand_rec.hdf5

reconstruction_config:
    bias: 1.4
    f: 0.87
    Omega_m: 0.3
    R_smooth: 15
    RSD_convention: RecSym
    hdf5_preffix: '/galaxies'

