input:
    input_path: ./test
    data_fname: test_data.fits
    randoms1_fname: test_randoms.fits
    randoms2_fname: test_randoms.fits

output:
    output_path: ./test
    displaced_catalog_fname: data_rec.fits
    shifted_random_catalog_fname: rand_rec.fits

reconstruction_config:
    bias: 1.4
    f: 0.87
    Omega_m: 0.3
    R_smooth: 15
    RSD_convention: RecSym

