input:
    input_path: ./test
    data_fname: test_data.fh
    randoms1_fname: test_randoms.fh
    randoms2_fname: test_randoms.fh

output:
    output_path: ./test
    displaced_catalog_fname: data_rec.fh
    shifted_random_catalog_fname: rand_rec.fh

reconstruction_config:
    bias: 1.4
    f: 0.87
    Omega_m: 0.3
    R_smooth: 15
    RSD_convention: RecSym

